// space-relay-v1 wire contract test.
//
// The fixture (test/fixtures/space-relay-v1.json) is generated by
// tools/generate-relay-fixtures.mjs and is shared byte-for-byte with the
// backend (entropydrop_backend/tests/fixtures/space-relay-v1.json, enforced by
// tests/test_space_relay_contract.py). Both tests pin the frame names and
// field shapes documented in docs/networking.md.
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import test from 'node:test';
import assert from 'node:assert/strict';
import { decode } from '@msgpack/msgpack';
import { parseRealtimePlayers } from '../src/engine/network/MultiplayerSync.ts';
import {
  DEFAULT_PLAYER_SKIN_URL,
  encodePlayerPosition,
} from '../src/bootstrap/SpaceBootstrap.ts';

const FIXTURE = JSON.parse(readFileSync(
  fileURLToPath(new URL('./fixtures/space-relay-v1.json', import.meta.url)),
  'utf8',
)) as {
  protocol: string;
  _note: string;
  frames: Record<string, { direction: 'client' | 'server'; msgpack_base64: string }>;
};

function frameBytes(name: string): Uint8Array {
  const frame = FIXTURE.frames[name];
  assert.ok(frame, `unknown fixture frame ${name}`);
  assert.equal(frame.direction, name.endsWith('_client') ? 'client' : 'server');
  return Uint8Array.from(Buffer.from(frame.msgpack_base64, 'base64'));
}

function frame(name: string): Record<string, unknown> {
  const decoded = decode(frameBytes(name));
  assert.equal(typeof decoded, 'object');
  return decoded as Record<string, unknown>;
}

const Q15_RANGE = 32767;

test('fixture targets the space-relay-v1 subprotocol', () => {
  assert.equal(FIXTURE.protocol, 'space-relay-v1');
});

test('client frames carry only the documented space-relay-v1 fields', () => {
  const hello = frame('hello_client');
  assert.deepEqual(hello, { type: 'hello', ticket: hello.ticket });
  assert.equal(typeof hello.ticket, 'string');

  const pose = frame('pose_client');
  assert.deepEqual(pose, {
    type: 'pose',
    sequence: pose.sequence,
    x_cm: pose.x_cm,
    y_cm: pose.y_cm,
    z_cm: pose.z_cm,
    yaw_q15: pose.yaw_q15,
    pitch_q15: pose.pitch_q15,
  });
  assert.ok(Number.isSafeInteger(pose.sequence));
  for (const field of ['x_cm', 'y_cm', 'z_cm']) {
    assert.ok(Number.isInteger(pose[field]), `${field} must be integer centimetres`);
  }
  for (const field of ['yaw_q15', 'pitch_q15']) {
    const value = Number(pose[field]);
    assert.ok(Number.isInteger(value) && Math.abs(value) <= Q15_RANGE, `${field} must be Q15`);
  }

  const ping = frame('ping_client');
  assert.deepEqual(ping, { type: 'ping', client_time: ping.client_time });

  const leave = frame('leave_client');
  assert.deepEqual(leave, { type: 'leave' });
});

test('server frames carry only the documented space-relay-v1 fields', () => {
  const hello = frame('hello_server');
  assert.deepEqual(hello, {
    type: 'hello',
    protocol: 'space-relay-v1',
    input_hz: 20,
    snapshot_hz: 10,
    persistence_seconds: 5,
  });

  const terrain = frame('terrain_server');
  assert.deepEqual(terrain, { type: 'terrain', terrain_revision: 12345 });

  const pong = frame('pong_server');
  assert.deepEqual(pong, { type: 'pong', client_time: 1_750_000_000_000 });

  const state = frame('state_server');
  assert.equal(state.type, 'state');
  assert.ok(Number.isSafeInteger(state.server_tick));
  assert.ok(Array.isArray(state.players));
  for (const player of state.players as Array<Record<string, unknown>>) {
    assert.deepEqual(Object.keys(player).sort(), [
      'is_self', 'pitch_q15', 'player_entity_id', 'skin_type', 'skin_url',
      'updated_at', 'user_id', 'username', 'x_cm', 'y_cm', 'yaw_q15', 'z_cm',
    ]);
    assert.equal(typeof player.user_id, 'string');
    assert.equal(typeof player.username, 'string');
    assert.equal(typeof player.player_entity_id, 'string');
    assert.equal(typeof player.skin_url, 'string');
    assert.ok(['strong', 'slim'].includes(String(player.skin_type)));
    for (const field of ['x_cm', 'y_cm', 'z_cm']) {
      assert.ok(Number.isInteger(player[field]), `${field} must be integer centimetres`);
    }
    assert.equal(typeof player.is_self, 'boolean');
    assert.ok(player.updated_at === null || typeof player.updated_at === 'string');
  }
});

test('state fixture normalizes through parseRealtimePlayers', () => {
  const state = frame('state_server');
  const players = parseRealtimePlayers(state.players, 'edSelf123');
  assert.equal(players.length, 2);
  assert.deepEqual(players[0], {
    user_id: 'edSelf123',
    username: 'Alice',
    player_entity_id: 'ent-aaaaaaaa-0001',
    skin_url: DEFAULT_PLAYER_SKIN_URL,
    skin_type: 'strong',
    x: 8192,
    y: 32,
    z: 1024,
    yaw: (16384 / Q15_RANGE) * Math.PI,
    pitch: 0,
    is_self: true,
    updated_at: null,
  });
  assert.deepEqual(players[1], {
    user_id: 'edOther456',
    username: 'Bob',
    player_entity_id: 'ent-bbbbbbbb-0002',
    skin_url: 'https://cdn.example/skins/bob.png',
    skin_type: 'slim',
    x: 0,
    y: 32,
    z: 1,
    yaw: (-16384 / Q15_RANGE) * Math.PI,
    pitch: (512 / Q15_RANGE) * Math.PI,
    is_self: false,
    updated_at: '2026-09-13T08:00:00Z',
  });
});

test('pose fixture matches the live client encoder', () => {
  const pose = frame('pose_client');
  const encoded = encodePlayerPosition({ x: 8192, y: 32, z: 1024 }, Math.PI / 2, 0);
  assert.deepEqual(encoded, {
    x_cm: Number(pose.x_cm),
    y_cm: Number(pose.y_cm),
    z_cm: Number(pose.z_cm),
    yaw_q15: Number(pose.yaw_q15),
    pitch_q15: Number(pose.pitch_q15),
  });
});

test('client frames respect the 4096-byte server inbound limit', () => {
  // SPACE_REALTIME_MAX_MESSAGE_BYTES in routers/space_realtime.py.
  for (const name of ['hello_client', 'pose_client', 'ping_client', 'leave_client']) {
    assert.ok(frameBytes(name).byteLength <= 4096, `${name} exceeds the inbound limit`);
  }
  assert.ok(frameBytes('hello_oversize_client').byteLength > 4096);
});
