"""Independent local Space schema; never creates cloud login or credit tables."""
from alembic import op
import sqlalchemy as sa
revision = 'space_0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('space_accounts',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('skin_url', sa.String(length=500), nullable=True),
    sa.Column('skin_type', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('space_hosting_authorizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('world_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('entity_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('settled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_space_hosting_authorizations_world_id'), 'space_hosting_authorizations', ['world_id'], unique=False)
    op.create_table('space_hosting_grants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('authorization_id', sa.String(length=36), nullable=False),
    sa.Column('world_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('entity_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('settlement', sa.String(length=16), nullable=True),
    sa.Column('settled', sa.Boolean(), nullable=False),
    sa.Column('error', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("state IN ('pending','ready','consumed','cancelled','failed')", name='ck_space_grant_state'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_space_hosting_grants_entity_id'), 'space_hosting_grants', ['entity_id'], unique=False)
    op.create_index(op.f('ix_space_hosting_grants_world_id'), 'space_hosting_grants', ['world_id'], unique=False)
    op.create_table('space_usage_buckets',
    sa.Column('principal_id', sa.String(length=64), nullable=False),
    sa.Column('scope_id', sa.String(length=64), nullable=False),
    sa.Column('metric', sa.String(length=48), nullable=False),
    sa.Column('window_seconds', sa.Integer(), nullable=False),
    sa.Column('bucket_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('used >= 0', name='ck_space_usage_bucket_used'),
    sa.CheckConstraint('window_seconds > 0', name='ck_space_usage_bucket_window'),
    sa.PrimaryKeyConstraint('principal_id', 'scope_id', 'metric', 'window_seconds', 'bucket_start')
    )
    op.create_index('ix_space_usage_buckets_retention', 'space_usage_buckets', ['metric', 'window_seconds', 'bucket_start'], unique=False)
    op.create_table('space_market_resources',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('publisher_user_id', sa.String(length=16), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('schema_version', sa.SmallInteger(), server_default='5', nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('license', sa.String(length=32), server_default='AGPL-3.0-only', nullable=False),
    sa.Column('content_digest', sa.LargeBinary(length=32), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('block_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('node_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('script_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('downloads_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('likes_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('blockset', 'entity', 'colorset')", name='ck_space_market_resource_kind'),
    sa.CheckConstraint("license = 'AGPL-3.0-only'", name='ck_space_market_resource_license'),
    sa.CheckConstraint('downloads_count >= 0 AND likes_count >= 0', name='ck_space_market_resource_counts'),
    sa.CheckConstraint('object_key IS NOT NULL', name='ck_space_market_resource_storage'),
    sa.CheckConstraint('schema_version = 5', name='ck_space_market_resource_schema_version'),
    sa.ForeignKeyConstraint(['publisher_user_id'], ['space_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_digest', name='uq_space_market_resource_digest')
    )
    op.create_index('ix_space_market_resources_downloads', 'space_market_resources', ['kind', 'downloads_count', 'created_at'], unique=False)
    op.create_index('ix_space_market_resources_latest', 'space_market_resources', ['kind', 'created_at'], unique=False)
    op.create_index('ix_space_market_resources_likes', 'space_market_resources', ['kind', 'likes_count', 'created_at'], unique=False)
    op.create_index('ix_space_market_resources_publisher_day', 'space_market_resources', ['publisher_user_id', 'created_at'], unique=False)
    op.create_table('worlds',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('owner_user_id', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('terrain_generator_version', sa.Integer(), nullable=False),
    sa.Column('protocol_version', sa.Integer(), nullable=False),
    sa.Column('width_chunks', sa.Integer(), nullable=False),
    sa.Column('length_chunks', sa.Integer(), nullable=False),
    sa.Column('zone_size_chunks', sa.Integer(), nullable=False),
    sa.Column('max_online_players', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['space_accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worlds_owner_user_id'), 'worlds', ['owner_user_id'], unique=False)
    op.create_table('chunk_snapshots',
    sa.Column('world_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('chunk_x', sa.Integer(), nullable=False),
    sa.Column('chunk_z', sa.Integer(), nullable=False),
    sa.Column('revision', sa.BigInteger(), nullable=False),
    sa.Column('last_event_id', sa.BigInteger(), nullable=False),
    sa.Column('codec', sa.SmallInteger(), nullable=False),
    sa.Column('codec_version', sa.SmallInteger(), nullable=False),
    sa.Column('uncompressed_size', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('payload', sa.LargeBinary(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('world_id', 'chunk_x', 'chunk_z')
    )
    op.create_index('chunk_snapshots_resume_idx', 'chunk_snapshots', ['world_id', 'last_event_id'], unique=False)
    op.create_index('ix_chunk_snapshots_world_revision', 'chunk_snapshots', ['world_id', 'revision'], unique=False)
    op.create_table('player_snapshots',
    sa.Column('world_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.String(length=16), nullable=False),
    sa.Column('revision', sa.BigInteger(), nullable=False),
    sa.Column('last_event_id', sa.BigInteger(), nullable=False),
    sa.Column('state_version', sa.SmallInteger(), nullable=False),
    sa.Column('state', sa.LargeBinary(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['space_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('world_id', 'user_id')
    )
    op.create_table('space_hosting_operations',
    sa.Column('world_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('operation_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('request_digest', sa.LargeBinary(length=32), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('world_id', 'operation_id')
    )
    op.create_table('space_hosting_workers',
    sa.Column('world_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('instance_id', sa.String(length=36), nullable=False),
    sa.Column('epoch', sa.BigInteger(), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('world_id')
    )
    op.create_table('space_market_resource_likes',
    sa.Column('resource_id', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['space_market_resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['space_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id', 'user_id')
    )
    op.create_table('space_surface_zone_snapshots',
    sa.Column('world_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('zone_x', sa.SmallInteger(), nullable=False),
    sa.Column('zone_z', sa.SmallInteger(), nullable=False),
    sa.Column('revision', sa.BigInteger(), nullable=False),
    sa.Column('source_terrain_revision', sa.BigInteger(), nullable=False),
    sa.Column('terrain_generator_version', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.SmallInteger(), nullable=False),
    sa.Column('samples_per_chunk_axis', sa.SmallInteger(), nullable=False),
    sa.Column('codec', sa.SmallInteger(), nullable=False),
    sa.Column('uncompressed_size', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('payload', sa.LargeBinary(), nullable=False),
    sa.Column('dirty', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('world_id', 'zone_x', 'zone_z')
    )
    op.create_index('ix_space_surface_zones_world_revision', 'space_surface_zone_snapshots', ['world_id', 'revision'], unique=False)
    op.create_table('space_terrain_mutation_batches',
    sa.Column('world_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('batch_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('actor_user_id', sa.String(length=16), nullable=True),
    sa.Column('dedupe_epoch', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('client_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('dedupe_epoch = 0 OR client_created_at IS NOT NULL', name='ck_space_terrain_batches_epoch_timestamp'),
    sa.CheckConstraint('dedupe_epoch IN (0, 1)', name='ck_space_terrain_batches_epoch'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['space_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('world_id', 'batch_id')
    )
    op.create_index('ix_space_terrain_batches_retention', 'space_terrain_mutation_batches', ['dedupe_epoch', 'client_created_at'], unique=False)
    op.create_table('space_world_entities',
    sa.Column('world_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('owner_user_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('schema_version', sa.SmallInteger(), server_default='5', nullable=False),
    sa.Column('content_digest', sa.LargeBinary(length=32), nullable=False),
    sa.Column('definition', sa.LargeBinary(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.LargeBinary(), nullable=True),
    sa.Column('snapshot_digest', sa.LargeBinary(length=32), nullable=True),
    sa.Column('snapshot_size_bytes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('position_x_cm', sa.Integer(), nullable=False),
    sa.Column('position_y_cm', sa.Integer(), nullable=False),
    sa.Column('position_z_cm', sa.Integer(), nullable=False),
    sa.Column('yaw_quarter_turns', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('desired_run_state', sa.String(length=16), server_default='running', nullable=False),
    sa.Column('revision', sa.BigInteger(), server_default='1', nullable=False),
    sa.Column('create_operation_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('create_request_digest', sa.LargeBinary(length=32), nullable=False),
    sa.Column('last_control_operation_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('last_checkpoint_operation_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('last_checkpoint_request_digest', sa.LargeBinary(length=32), nullable=True),
    sa.Column('execution_instance_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('execution_lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_epoch', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('execution_mode', sa.String(length=16), server_default='browser', nullable=False),
    sa.Column('hosting_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('hosting_remaining_ms', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('hosting_budget_remaining', sa.Integer(), server_default='0', nullable=False),
    sa.Column('hosting_billed_hours', sa.Integer(), server_default='0', nullable=False),
    sa.Column('hosting_authorization_id', sa.String(length=36), nullable=True),
    sa.Column('hosting_anchor', sa.JSON(), nullable=True),
    sa.Column('hosting_reason', sa.String(length=80), nullable=True),
    sa.Column('hosting_error', sa.String(length=500), nullable=True),
    sa.Column('hosting_last_tick_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("NOT hosting_enabled OR (execution_mode = 'hosted' AND desired_run_state = 'running')", name='ck_space_hosting_enabled'),
    sa.CheckConstraint("desired_run_state IN ('running', 'stopped')", name='ck_space_world_entity_run_state'),
    sa.CheckConstraint("execution_mode IN ('browser', 'hosted')", name='ck_space_hosting_mode'),
    sa.CheckConstraint('execution_epoch >= 0', name='ck_space_world_entity_execution_epoch'),
    sa.CheckConstraint('hosting_billed_hours >= 0', name='ck_space_hosting_billed'),
    sa.CheckConstraint('hosting_budget_remaining BETWEEN 0 AND 168', name='ck_space_hosting_budget'),
    sa.CheckConstraint('hosting_remaining_ms BETWEEN 0 AND 3600000', name='ck_space_hosting_time'),
    sa.CheckConstraint('revision >= 1', name='ck_space_world_entity_revision'),
    sa.CheckConstraint('size_bytes > 0', name='ck_space_world_entity_size'),
    sa.CheckConstraint('snapshot_size_bytes >= 0', name='ck_space_world_entity_snapshot_size'),
    sa.CheckConstraint('yaw_quarter_turns >= 0 AND yaw_quarter_turns <= 3', name='ck_space_world_entity_yaw'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['space_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('world_id', 'id'),
    sa.UniqueConstraint('world_id', 'owner_user_id', 'create_operation_id', name='uq_space_world_entity_create_operation')
    )
    op.create_index('ix_space_world_entities_owner', 'space_world_entities', ['world_id', 'owner_user_id', 'created_at'], unique=False)
    op.create_index('ix_space_world_entities_world_position', 'space_world_entities', ['world_id', 'position_x_cm', 'position_z_cm'], unique=False)
    op.create_table('world_event_streams',
    sa.Column('world_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('last_event_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('world_id')
    )
    op.create_table('world_player_profiles',
    sa.Column('world_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.String(length=16), nullable=False),
    sa.Column('player_entity_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['space_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('world_id', 'user_id'),
    sa.UniqueConstraint('world_id', 'player_entity_id', name='uq_world_player_entity')
    )
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('world_player_profiles')
    op.drop_table('world_event_streams')
    op.drop_index('ix_space_world_entities_world_position', table_name='space_world_entities')
    op.drop_index('ix_space_world_entities_owner', table_name='space_world_entities')
    op.drop_table('space_world_entities')
    op.drop_index('ix_space_terrain_batches_retention', table_name='space_terrain_mutation_batches')
    op.drop_table('space_terrain_mutation_batches')
    op.drop_index('ix_space_surface_zones_world_revision', table_name='space_surface_zone_snapshots')
    op.drop_table('space_surface_zone_snapshots')
    op.drop_table('space_market_resource_likes')
    op.drop_table('space_hosting_workers')
    op.drop_table('space_hosting_operations')
    op.drop_table('player_snapshots')
    op.drop_index('ix_chunk_snapshots_world_revision', table_name='chunk_snapshots')
    op.drop_index('chunk_snapshots_resume_idx', table_name='chunk_snapshots')
    op.drop_table('chunk_snapshots')
    op.drop_index(op.f('ix_worlds_owner_user_id'), table_name='worlds')
    op.drop_table('worlds')
    op.drop_index('ix_space_market_resources_publisher_day', table_name='space_market_resources')
    op.drop_index('ix_space_market_resources_likes', table_name='space_market_resources')
    op.drop_index('ix_space_market_resources_latest', table_name='space_market_resources')
    op.drop_index('ix_space_market_resources_downloads', table_name='space_market_resources')
    op.drop_table('space_market_resources')
    op.drop_index('ix_space_usage_buckets_retention', table_name='space_usage_buckets')
    op.drop_table('space_usage_buckets')
    op.drop_index(op.f('ix_space_hosting_grants_world_id'), table_name='space_hosting_grants')
    op.drop_index(op.f('ix_space_hosting_grants_entity_id'), table_name='space_hosting_grants')
    op.drop_table('space_hosting_grants')
    op.drop_index(op.f('ix_space_hosting_authorizations_world_id'), table_name='space_hosting_authorizations')
    op.drop_table('space_hosting_authorizations')
    op.drop_table('space_accounts')
    # ### end Alembic commands ###
