# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: space/contracts/space_api.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'space/contracts/space_api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fspace/contracts/space_api.proto\x12\x18\x65ntropydrop.space.api.v2\"6\n\nPositionCm\x12\x0c\n\x04x_cm\x18\x01 \x01(\x11\x12\x0c\n\x04y_cm\x18\x02 \x01(\x11\x12\x0c\n\x04z_cm\x18\x03 \x01(\x11\"\xee\x01\n\x13\x43reateEntityRequest\x12\x14\n\x0coperation_id\x18\x01 \x01(\t\x12\x12\n\ndefinition\x18\x02 \x01(\x0c\x12\x36\n\x08position\x18\x03 \x01(\x0b\x32$.entropydrop.space.api.v2.PositionCm\x12\x19\n\x11yaw_quarter_turns\x18\x04 \x01(\r\x12\x43\n\x11\x64\x65sired_run_state\x18\x05 \x01(\x0e\x32(.entropydrop.space.api.v2.EntityRunState\x12\x15\n\rsnapshot_json\x18\x06 \x01(\x0c\"\xf2\x01\n\x17\x43heckpointEntityRequest\x12\x14\n\x0coperation_id\x18\x01 \x01(\t\x12\x19\n\x11\x65xpected_revision\x18\x02 \x01(\x04\x12\x12\n\ndefinition\x18\x03 \x01(\x0c\x12\x36\n\x08position\x18\x04 \x01(\x0b\x32$.entropydrop.space.api.v2.PositionCm\x12\x43\n\x11\x64\x65sired_run_state\x18\x05 \x01(\x0e\x32(.entropydrop.space.api.v2.EntityRunState\x12\x15\n\rsnapshot_json\x18\x06 \x01(\x0c\"\xaa\x01\n\x14\x42uildBlocksetRequest\x12\x14\n\x0coperation_id\x18\x01 \x01(\t\x12\x15\n\rcreated_at_ms\x18\x02 \x01(\x04\x12\x12\n\ndefinition\x18\x03 \x01(\x0c\x12\x36\n\x08position\x18\x04 \x01(\x0b\x32$.entropydrop.space.api.v2.PositionCm\x12\x19\n\x11yaw_quarter_turns\x18\x05 \x01(\r*L\n\x0e\x45ntityRunState\x12\x1c\n\x18\x45NTITY_RUN_STATE_STOPPED\x10\x00\x12\x1c\n\x18\x45NTITY_RUN_STATE_RUNNING\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'space.contracts.space_api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENTITYRUNSTATE']._serialized_start=776
  _globals['_ENTITYRUNSTATE']._serialized_end=852
  _globals['_POSITIONCM']._serialized_start=61
  _globals['_POSITIONCM']._serialized_end=115
  _globals['_CREATEENTITYREQUEST']._serialized_start=118
  _globals['_CREATEENTITYREQUEST']._serialized_end=356
  _globals['_CHECKPOINTENTITYREQUEST']._serialized_start=359
  _globals['_CHECKPOINTENTITYREQUEST']._serialized_end=601
  _globals['_BUILDBLOCKSETREQUEST']._serialized_start=604
  _globals['_BUILDBLOCKSETREQUEST']._serialized_end=774
# @@protoc_insertion_point(module_scope)
