"""space-relay-v1 wire contract tests.

The fixture (tests/fixtures/space-relay-v1.json) is shared byte-for-byte with
the frontend checkout (entropydrop_space/client/test/fixtures/
space-relay-v1.json, generated by client/tools/generate-relay-fixtures.mjs
and pinned by client/test/space-relay-v1.test.ts). Both sides pin the
frame names and field shapes documented in
entropydrop_space/client/docs/networking.md.
"""
import base64
import json
from pathlib import Path

import msgpack
import pytest

from routers.space_realtime import SPACE_REALTIME_MAX_MESSAGE_BYTES, _unpack_message
from space.entity_pose import parse_entity_pose

ROOT = Path(__file__).resolve().parents[1]
FIXTURE_PATH = Path(__file__).resolve().parent / "fixtures" / "space-relay-v1.json"
SIBLING_FIXTURE_PATH = (
    ROOT.parent / "client" / "test" / "fixtures" / "space-relay-v1.json"
)

FIXTURE = json.loads(FIXTURE_PATH.read_text())
FRAMES = FIXTURE["frames"]


def frame_bytes(name: str) -> bytes:
    return base64.b64decode(FRAMES[name]["msgpack_base64"])


def frame(name: str) -> dict:
    return msgpack.unpackb(frame_bytes(name), raw=False, strict_map_key=False)


def test_fixture_targets_space_relay_v1():
    assert FIXTURE["protocol"] == "space-relay-v1"


def test_client_frames_carry_only_documented_fields():
    hello = frame("hello_client")
    assert set(hello) == {"type", "ticket"}
    assert hello["type"] == "hello"
    assert isinstance(hello["ticket"], str)

    pose = frame("pose_client")
    assert set(pose) == {"type", "sequence", "x_cm", "y_cm", "z_cm", "yaw_q15", "pitch_q15"}
    assert pose["type"] == "pose"
    assert isinstance(pose["sequence"], int)
    for field in ("x_cm", "y_cm", "z_cm", "yaw_q15", "pitch_q15"):
        assert isinstance(pose[field], int)
    assert abs(pose["yaw_q15"]) <= 32767
    assert abs(pose["pitch_q15"]) <= 32767

    ping = frame("ping_client")
    assert set(ping) == {"type", "client_time"}
    assert ping["type"] == "ping"

    leave = frame("leave_client")
    assert leave == {"type": "leave"}


def test_server_frames_carry_only_documented_fields():
    hello = frame("hello_server")
    assert hello == {
        "type": "hello",
        "protocol": "space-relay-v1",
        "input_hz": 20,
        "snapshot_hz": 10,
        "persistence_seconds": 5,
        "entity_pose_hz": 20,
    }

    terrain = frame("terrain_server")
    assert terrain == {"type": "terrain", "terrain_revision": 12345}

    pong = frame("pong_server")
    assert pong == {"type": "pong", "client_time": 1_750_000_000_000}

    state = frame("state_server")
    assert state["type"] == "state"
    assert isinstance(state["server_tick"], int)
    assert isinstance(state["players"], list)
    for player in state["players"]:
        assert set(player) == {
            "user_id", "username", "player_entity_id", "skin_url", "skin_type",
            "x_cm", "y_cm", "z_cm", "yaw_q15", "pitch_q15", "is_self", "updated_at",
        }
        assert isinstance(player["user_id"], str)
        assert isinstance(player["username"], str)
        assert isinstance(player["player_entity_id"], str)
        assert isinstance(player["skin_url"], str)
        assert player["skin_type"] in ("strong", "slim")
        assert isinstance(player["is_self"], bool)
        assert player["updated_at"] is None or isinstance(player["updated_at"], str)
        for field in ("x_cm", "y_cm", "z_cm", "yaw_q15", "pitch_q15"):
            assert isinstance(player[field], int)
            if field in ("yaw_q15", "pitch_q15"):
                assert abs(player[field]) <= 32767


def test_inbound_frames_respect_the_size_limit():
    assert SPACE_REALTIME_MAX_MESSAGE_BYTES == 4096
    for name in ("hello_client", "pose_client", "ping_client", "leave_client"):
        # The relay enforces the limit on the exact bytes it receives.
        payload = _unpack_message(frame_bytes(name))
        assert payload["type"] in ("hello", "pose", "ping", "leave")
    with pytest.raises(ValueError, match="too large"):
        _unpack_message(frame_bytes("hello_oversize_client"))


def test_fixture_matches_sibling_frontend_copy():
    if not SIBLING_FIXTURE_PATH.is_file():
        pytest.skip("sibling entropydrop_space checkout is not present")
    assert SIBLING_FIXTURE_PATH.read_bytes() == FIXTURE_PATH.read_bytes(), (
        "tests/fixtures/space-relay-v1.json drifted from the frontend copy; "
        "re-run client/tools/generate-relay-fixtures.mjs and re-copy the output"
    )


def test_entity_pose_frames_hide_executor_capability_and_pin_vectors():
    sent = parse_entity_pose(_unpack_message(frame_bytes('entity_pose_client')))
    received = frame('entity_state_server')
    assert received['type'] == 'entity_state'
    item = received['items'][0]
    assert set(item) == {'entity_id', 'execution_epoch', 'sequence', 'revision',
                         'definition_digest', 'lease_expires_at', 'bodies'}
    assert item['bodies'] == sent['bodies']
    assert 'instance_id' not in item
